#!/usr/bin/env bash
# this script will return details on a domain

print_ () {
        sub=$2
        main=$1
        details=$(dig "$sub.$main" | grep -A1 'ANSWER SECTION:' | tail -1)
        sent=$(echo "$details" | awk -v s="$sub" '{print "The subdomain "}{print s}{print " is a "}{print $4}{print " record and points to "}{print $5}')
        echo $sent
}

if [ $# -eq 2 ]; then

        print_ "$1" "$2"
else
        for sub in 'www' 'lb-01' 'web-01' 'web-02'
        do
                print_ "$1" "$sub"
        done
fi
