#!/usr/bin/env bash
# We will output the subdirectory, record_type, and destination

if [ "$#" -eq 1 ]; then
   for i in "www" "lb-01" "web-01" "web-02"
   do
       RECORD_TYPE=$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
       DESTINATION=$(dig "$i"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
       echo "The subdomain $i is a $RECORD_TYPE record and points to $DESTINATION"
   done
elif [ "$#" -eq 2 ]; then
    RECORD_TYPE=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4}')
    DESTINATION=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $5}')
    echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
fi