#!/usr/bin/env bash
#Install nginx web server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
sudo service nginx start
