#!/usr/bin/env bash
# This script configure haproxy load balancer
sudo apt-get install software-properties-common -y
sudo add-apt-repository ppa:vbernat/haproxy-2.0 -y
sudo apt-get update
sudo apt-get install haproxy=2.0.\* -y
echo 35.237.122.227 750-web-01 | sudo tee -a /etc/hosts
echo 35.237.198.85 750-web-02 | sudo tee -a /etc/hosts
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig
echo -e "\nfrontend http_front\n\tbind *:80\n\tdefault_backend http_back\n" | sudo tee -a /etc/haproxy/haproxy.cfg
echo -e "\nbackend http_back\n\tbalance roundrobin\n\tserver 750-web-01 35.237.122.227:80 check\n\tserver 750-web-02 35.237.198.85:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy start
