#!/usr/bin/env bash
# Script that installs and configures HAproxy on the 1b-01 server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5

sudo apt-get -y update
sudo apt-get -y install haproxy

listen_string="listen Holberton 0.0.0.0:80\n\tmode http\n\tstats enable\n\tbalance roundrobin\n\tserer 136-web-01 35.237.122.227 check\n\tserver 136-web-02 35.237.198.85 check"

sudo sed -i '8 i ENABLED=1' /etc/default/haproxy
sudo sed -i -e "\$a$listen_string" /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy restart