#!/usr/bin/env bash
# displays Holberton School 10 times, but for the 9th iteration, displays Hi.

count=0

while((count <= 10))
do
	if ((count == 9)); then
		echo Hi
	else
		echo Holberton School
	fi
	((count ++))
done
