#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and:

cont=0

while((cont<20)); do
    echo "$cont"
	case "$cont" in
	4) echo "bad luck from China";;
	9) echo "bad luck from Japan";;
	17) echo "bad luck from Italy";;
	esac

	((cont ++))
done
