#!/usr/bin/env bash
#  script that displays the time for 12 hours and 59 minutes:

hours=0

while((hours<=12)); do
    echo "Hour: $hours"
    min=1
    while((min<=59)); do
        echo $min
	((min ++))
    done
    ((hours ++))
done
